### ISSUE TITLE
2021/01/31 rails c が動かない

### ISSUE THREAD

**Issue by atarubift** [atarubift/todo#21]
## 内容
`rails c`を入力すると下記のエラーになる

```
/usr/lib/ruby/2.7.0/x86_64-linux/stringio.so: warning: already initialized constant StringIO::VERSION
/usr/lib/ruby/2.7.0/mutex_m.rb:43: warning: already initialized constant Mutex_m::VERSION
/home/ataruby/.gem/ruby/2.7.0/gems/mutex_m-0.1.1/lib/mutex_m.rb:43: warning: previous definition of VERSION was here
Running via Spring preloader in process 2566
Traceback (most recent call last):
/home/ataruby/.gem/ruby/2.7.0/gems/activesupport-6.1.0/lib/active_support/fork_tracker.rb:8:in `fork': Bootsnap::LoadPathCache::FallbackScan
	37: from -e:1:in `<main>'
	36: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	35: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	34: from /home/ataruby/.gem/ruby/2.7.0/gems/activesupport-6.1.0/lib/active_support/fork_tracker.rb:26:in `fork'
	33: from /home/ataruby/.gem/ruby/2.7.0/gems/activesupport-6.1.0/lib/active_support/fork_tracker.rb:8:in `fork'
	32: from /home/ataruby/.gem/ruby/2.7.0/gems/activesupport-6.1.0/lib/active_support/fork_tracker.rb:8:in `fork'
	31: from /home/ataruby/.gem/ruby/2.7.0/gems/activesupport-6.1.0/lib/active_support/fork_tracker.rb:10:in `block in fork'
	30: from /usr/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
	29: from /usr/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
	28: from /home/ataruby/Desktop/railsProject/sample_app/bin/rails:5:in `<main>'
	27: from /home/ataruby/.gem/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	26: from /usr/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	25: from /usr/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	24: from /usr/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	23: from /usr/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	22: from /usr/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	21: from /home/ataruby/.gem/ruby/2.7.0/gems/railties-6.1.0/lib/rails/commands.rb:18:in `<main>'
	20: from /home/ataruby/.gem/ruby/2.7.0/gems/railties-6.1.0/lib/rails/command.rb:48:in `invoke'
	19: from /home/ataruby/.gem/ruby/2.7.0/gems/railties-6.1.0/lib/rails/command.rb:76:in `find_by_namespace'
	18: from /home/ataruby/.gem/ruby/2.7.0/gems/railties-6.1.0/lib/rails/command/behavior.rb:39:in `lookup'
	17: from /home/ataruby/.gem/ruby/2.7.0/gems/railties-6.1.0/lib/rails/command/behavior.rb:39:in `each'
	16: from /home/ataruby/.gem/ruby/2.7.0/gems/railties-6.1.0/lib/rails/command/behavior.rb:40:in `block in lookup'
	15: from /home/ataruby/.gem/ruby/2.7.0/gems/railties-6.1.0/lib/rails/command/behavior.rb:40:in `each'
	14: from /home/ataruby/.gem/ruby/2.7.0/gems/railties-6.1.0/lib/rails/command/behavior.rb:44:in `block (2 levels) in lookup'
	13: from /home/ataruby/.gem/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	12: from /usr/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	11: from /usr/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	10: from /usr/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	 9: from /usr/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	 8: from /usr/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	 7: from /home/ataruby/.gem/ruby/2.7.0/gems/railties-6.1.0/lib/rails/commands/console/console_command.rb:3:in `<main>'
	 6: from /home/ataruby/.gem/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	 5: from /usr/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:26:in `require'
	 4: from /usr/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:40:in `rescue in require'
	 3: from /usr/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	 2: from /usr/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:89:in `register'
	 1: from /usr/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/usr/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require': cannot load such file -- irb (LoadError)
```

念の為、rb-readlineをインストールしたが結果は変わらなかった。

**Comment by atarubift** [comment]
他のrails Appでも同様のエラーが出たため、rb-readlineは関係なさそう

**Comment by atarubift** [comment]
ruby, rbenv の再インストール
pathの設定を行った結果動くようになった
